### ISSUE TITLE
Good Documentation

### ISSUE THREAD

**Issue by Mr-Emerald-Wolf** [Mr-Emerald-Wolf/raog#1]
Our app needs good documentation. Please contribute more information to our readme.

**Comment by MahmoudDawood** [comment]
Do you have a specific description of the project and its purpose? so I can start making it the way it's intended to be.

**Comment by Mr-Emerald-Wolf** [comment]
We are still figuring out the features of our app. Our Idea:
 React app
- markdown to jsx (react) converter (maybe already exists) 
- takes markdown input from raog member, converts to jsx file which takes up a section (or div) of website, uses GitHub api to automatically authenticate and PR (or let them download the updated code and redirect to PR page.
- We still need to discuss if this is gonna be our final app. We are not so sure on the details.

**Comment by MahmoudDawood** [comment]
Looks interesting! I'd like to contribute to it, make an initial PR and see if it works fine.
Would you assign it to me?

**Comment by MahmoudDawood** [comment]
cc @Mr-Emerald-Wolf

**Comment by Mr-Emerald-Wolf** [comment]
Yes that sounds fine
